services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=django-db
      - DATABASE_URL=postgres://finance_user:finance_password@db:5432/finance_db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: finance_db
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: finance_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
  celery:
    build: .
    command: celery -A finance_api worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
volumes:
  postgres_data:
